import { appSchema, tableSchema } from "@nozbe/watermelondb";

import { DB_TABLES } from "@/src/utils/constants";

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: DB_TABLES.wagons,
      columns: [
        { name: "name", type: "string", isIndexed: true },
        { name: "name_search", type: "string", isIndexed: true },
        { name: "code", type: "string", isOptional: true },
        { name: "description", type: "string", isOptional: true },
        { name: "capacity_kg", type: "number", isOptional: true },
        { name: "inner_length_mm", type: "number", isOptional: true },
        { name: "inner_width_mm", type: "number", isOptional: true },
        { name: "inner_height_mm", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_deleted", type: "boolean" },
        { name: "sync_status", type: "string" },
        { name: "version", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.packageTypes,
      columns: [
        { name: "package_type_number", type: "number", isIndexed: true },
        { name: "construction_variant", type: "string", isIndexed: true },
        { name: "nominal_ingot_mass_kg", type: "number" },
        { name: "ingot_height_mm", type: "number" },
        { name: "package_dimensions", type: "string" },
        { name: "leg_height_mm", type: "number" },
        { name: "leg_base_mm", type: "number" },
        { name: "nominal_package_mass_kg", type: "number" },
        { name: "package_mass_deviation_kg", type: "number" },
        { name: "search_label", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_deleted", type: "boolean" },
        { name: "sync_status", type: "string" },
        { name: "version", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.loadingSchemes,
      columns: [
        { name: "group_key", type: "string", isIndexed: true },
        { name: "name", type: "string", isIndexed: true },
        { name: "description", type: "string", isOptional: true },
        { name: "image_key", type: "string" },
        { name: "tiers_count", type: "number" },
        { name: "tier_order_number", type: "number" },
        { name: "wagon_id", type: "string", isIndexed: true },
        { name: "package_type_id", type: "string", isIndexed: true },
        { name: "instruction_text", type: "string" },
        { name: "tier_note", type: "string", isOptional: true },
        { name: "is_active", type: "boolean" },
        { name: "version", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_deleted", type: "boolean" },
        { name: "sync_status", type: "string" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.inventoryItems,
      columns: [
        { name: "name", type: "string", isIndexed: true },
        { name: "name_search", type: "string", isIndexed: true },
        { name: "quantity", type: "number" },
        { name: "configuration", type: "string" },
        { name: "image_key", type: "string", isOptional: true },
        { name: "unit_of_measure", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_deleted", type: "boolean" },
        { name: "sync_status", type: "string" },
        { name: "version", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.schemeInventories,
      columns: [
        { name: "loading_scheme_id", type: "string", isIndexed: true },
        { name: "inventory_item_id", type: "string", isIndexed: true },
        { name: "units_count", type: "number" },
        { name: "note", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.loadingReports,
      columns: [
        { name: "date_time", type: "number", isIndexed: true },
        { name: "wagon_id", type: "string", isIndexed: true },
        { name: "package_type_id", type: "string", isIndexed: true },
        { name: "selected_scheme_group_key", type: "string", isIndexed: true },
        { name: "selected_tier_ids_json", type: "string" },
        { name: "used_inventory_json", type: "string" },
        { name: "result_text", type: "string" },
        { name: "result_html", type: "string" },
        { name: "txt_path", type: "string", isOptional: true },
        { name: "pdf_path", type: "string", isOptional: true },
        { name: "status", type: "string", isIndexed: true },
        { name: "operator_comment", type: "string", isOptional: true },
        { name: "operator_name", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_deleted", type: "boolean" },
        { name: "sync_status", type: "string" },
        { name: "version", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.appSettings,
      columns: [
        { name: "key", type: "string", isIndexed: true },
        { name: "value", type: "string" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: DB_TABLES.seedMeta,
      columns: [
        { name: "seed_version", type: "string", isIndexed: true },
        { name: "applied_at", type: "number" },
        { name: "checksum", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: DB_TABLES.auditLogs,
      columns: [
        { name: "entity_type", type: "string", isIndexed: true },
        { name: "entity_id", type: "string", isIndexed: true },
        { name: "action", type: "string", isIndexed: true },
        { name: "payload_json", type: "string" },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),
    tableSchema({
      name: DB_TABLES.syncQueue,
      columns: [
        { name: "entity_type", type: "string", isIndexed: true },
        { name: "entity_id", type: "string", isIndexed: true },
        { name: "operation", type: "string" },
        { name: "payload_json", type: "string" },
        { name: "status", type: "string", isIndexed: true },
        { name: "attempts", type: "number" },
      ],
    }),
  ],
});
