import type { InventoryItemRecord, SchemeInventoryRecord } from "@/src/types/domain";

const timestamp = 1711260000000;

export const inventoryItemsSeed: InventoryItemRecord[] = [
  {
    id: "inv-wood-pad",
    name: "Деревянная прокладка",
    quantity: 4,
    configuration: "1000 x 120 x 80 мм",
    imageKey: "scheme-inline-01.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-beam",
    name: "Разделительная балка",
    quantity: 2,
    configuration: "1200 x 180 x 120 мм",
    imageKey: "scheme-inline-02.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-corner",
    name: "Угловая защита",
    quantity: 8,
    configuration: "Сталь 3 мм, оцинкованная",
    imageKey: "scheme-inline-03.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-chain",
    name: "Цепь крепежная",
    quantity: 4,
    configuration: "Ø 10 мм, длина 4 м",
    imageKey: "scheme-inline-04.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-belt",
    name: "Поясная стяжка",
    quantity: 6,
    configuration: "Лента 50 мм, храповик",
    imageKey: "scheme-inline-05.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-side-stop",
    name: "Боковой упор",
    quantity: 6,
    configuration: "Усиленный, L-образный",
    imageKey: "scheme-inline-06.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-wedge",
    name: "Клин фиксирующий",
    quantity: 8,
    configuration: "Деревянный, 220 мм",
    imageKey: "scheme-inline-01.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-wire",
    name: "Проволочная обвязка",
    quantity: 12,
    configuration: "Ø 6 мм, бухта",
    imageKey: "scheme-inline-02.png",
    unitOfMeasure: "м",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-mat",
    name: "Противоскользящий мат",
    quantity: 6,
    configuration: "Резиновый, 1000 x 300 мм",
    imageKey: "scheme-inline-03.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-rack",
    name: "Распорная рама",
    quantity: 2,
    configuration: "Стальная, регулируемая",
    imageKey: "scheme-inline-04.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-protector",
    name: "Торцевой защитный щит",
    quantity: 2,
    configuration: "Лист 900 x 600 мм",
    imageKey: "scheme-inline-05.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "inv-strap",
    name: "Диагональная стропа",
    quantity: 4,
    configuration: "Полиэстер 75 мм",
    imageKey: "scheme-inline-06.png",
    unitOfMeasure: "шт",
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
];

export const schemeInventorySeed: SchemeInventoryRecord[] = [
  { id: "rel-001", loadingSchemeId: "scheme-compact-01-tier-1", inventoryItemId: "inv-wood-pad", unitsCount: 4, note: "Под каждый угол пакета", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-002", loadingSchemeId: "scheme-compact-01-tier-1", inventoryItemId: "inv-side-stop", unitsCount: 4, note: "Фиксация по торцам", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-003", loadingSchemeId: "scheme-cross-02-tier-1", inventoryItemId: "inv-mat", unitsCount: 4, note: "Под первый ряд", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-004", loadingSchemeId: "scheme-cross-02-tier-1", inventoryItemId: "inv-side-stop", unitsCount: 4, note: "По бортам", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-005", loadingSchemeId: "scheme-cross-02-tier-2", inventoryItemId: "inv-belt", unitsCount: 4, note: "Финишная фиксация", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-006", loadingSchemeId: "scheme-cross-02-tier-2", inventoryItemId: "inv-corner", unitsCount: 8, note: "Защита от перетирания", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-007", loadingSchemeId: "scheme-high-03-tier-1", inventoryItemId: "inv-mat", unitsCount: 4, note: "Под нижний ярус", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-008", loadingSchemeId: "scheme-high-03-tier-1", inventoryItemId: "inv-wedge", unitsCount: 6, note: "Боковая стабилизация", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-009", loadingSchemeId: "scheme-high-03-tier-2", inventoryItemId: "inv-beam", unitsCount: 2, note: "Разделение между ярусами", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-010", loadingSchemeId: "scheme-high-03-tier-2", inventoryItemId: "inv-wood-pad", unitsCount: 4, note: "Под промежуточные опоры", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-011", loadingSchemeId: "scheme-high-03-tier-3", inventoryItemId: "inv-corner", unitsCount: 8, note: "Верхние углы", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-012", loadingSchemeId: "scheme-high-03-tier-3", inventoryItemId: "inv-belt", unitsCount: 4, note: "Финишная стяжка", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-013", loadingSchemeId: "scheme-platform-04-tier-1", inventoryItemId: "inv-chain", unitsCount: 4, note: "Фиксация к проушинам", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-014", loadingSchemeId: "scheme-platform-04-tier-1", inventoryItemId: "inv-side-stop", unitsCount: 4, note: "Ограничение ряда", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-015", loadingSchemeId: "scheme-platform-05-tier-1", inventoryItemId: "inv-mat", unitsCount: 4, note: "Под нижний ряд", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-016", loadingSchemeId: "scheme-platform-05-tier-1", inventoryItemId: "inv-protector", unitsCount: 2, note: "На торцы ряда", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-017", loadingSchemeId: "scheme-platform-05-tier-2", inventoryItemId: "inv-beam", unitsCount: 2, note: "Между рядами", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-018", loadingSchemeId: "scheme-platform-05-tier-2", inventoryItemId: "inv-strap", unitsCount: 4, note: "Обвязка по диагонали", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-019", loadingSchemeId: "scheme-covered-06-tier-1", inventoryItemId: "inv-wire", unitsCount: 12, note: "Обвязка по точкам фиксации", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-020", loadingSchemeId: "scheme-covered-06-tier-1", inventoryItemId: "inv-side-stop", unitsCount: 4, note: "Внутренние стойки", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-021", loadingSchemeId: "scheme-covered-07-tier-1", inventoryItemId: "inv-beam", unitsCount: 2, note: "Базовые направляющие", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-022", loadingSchemeId: "scheme-covered-07-tier-1", inventoryItemId: "inv-wedge", unitsCount: 6, note: "Боковая стабилизация", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-023", loadingSchemeId: "scheme-covered-07-tier-2", inventoryItemId: "inv-rack", unitsCount: 2, note: "Распорные рамы", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-024", loadingSchemeId: "scheme-covered-07-tier-2", inventoryItemId: "inv-belt", unitsCount: 4, note: "Поясное крепление", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-025", loadingSchemeId: "scheme-covered-07-tier-3", inventoryItemId: "inv-wire", unitsCount: 12, note: "Финишная проволока", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-026", loadingSchemeId: "scheme-covered-07-tier-3", inventoryItemId: "inv-corner", unitsCount: 8, note: "Защита верхнего яруса", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-027", loadingSchemeId: "scheme-halfcar-08-tier-1", inventoryItemId: "inv-chain", unitsCount: 4, note: "По диагонали", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-028", loadingSchemeId: "scheme-halfcar-08-tier-1", inventoryItemId: "inv-side-stop", unitsCount: 4, note: "Для удержания центра", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-029", loadingSchemeId: "scheme-halfcar-09-tier-1", inventoryItemId: "inv-wedge", unitsCount: 6, note: "Шахматная стабилизация", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-030", loadingSchemeId: "scheme-halfcar-09-tier-1", inventoryItemId: "inv-wood-pad", unitsCount: 4, note: "Под опоры пакета", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-031", loadingSchemeId: "scheme-halfcar-09-tier-2", inventoryItemId: "inv-strap", unitsCount: 4, note: "Диагональная стяжка", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-032", loadingSchemeId: "scheme-halfcar-09-tier-2", inventoryItemId: "inv-corner", unitsCount: 8, note: "Углы под ленту", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-033", loadingSchemeId: "scheme-heavy-10-tier-1", inventoryItemId: "inv-mat", unitsCount: 4, note: "Усиленные маты", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-034", loadingSchemeId: "scheme-heavy-10-tier-1", inventoryItemId: "inv-chain", unitsCount: 4, note: "Двойная фиксация", createdAt: timestamp, updatedAt: timestamp },
  { id: "rel-035", loadingSchemeId: "scheme-heavy-10-tier-1", inventoryItemId: "inv-protector", unitsCount: 2, note: "Торцевая защита", createdAt: timestamp, updatedAt: timestamp },
];
