import type { LoadingSchemeTierRecord } from "@/src/types/domain";

const timestamp = 1711260000000;

export const loadingSchemesSeed: LoadingSchemeTierRecord[] = [
  {
    id: "scheme-compact-01-tier-1",
    groupKey: "scheme-compact-01",
    name: "Компактная укладка в полувагон",
    description: "Одноярусная схема для быстрого запуска смены.",
    imageKey: "scheme-inline-01.png",
    tiersCount: 1,
    tierOrderNumber: 1,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-01-i",
    instructionText: "Уложить пакеты по оси вагона, выставить упоры по торцам и затянуть стяжку.",
    tierNote: "Контроль зазора между пакетами не более 40 мм.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-cross-02-tier-1",
    groupKey: "scheme-cross-02",
    name: "Перекрестная укладка",
    description: "Двухъярусная схема с чередованием пакетов.",
    imageKey: "scheme-inline-02.png",
    tiersCount: 2,
    tierOrderNumber: 1,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-02-ii",
    instructionText: "Сформировать нижний ярус с перекрестным смещением и установить торцевые упоры.",
    tierNote: "Следить за симметрией относительно центра вагона.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-cross-02-tier-2",
    groupKey: "scheme-cross-02",
    name: "Перекрестная укладка",
    description: "Верхний ярус со страховочными поясами.",
    imageKey: "scheme-inline-03.png",
    tiersCount: 2,
    tierOrderNumber: 2,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-02-ii",
    instructionText: "Уложить верхний ярус с прокладками и закрепить пакетные пояса через боковые скобы.",
    tierNote: "После завершения проверить натяжение поясных стяжек.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-high-03-tier-1",
    groupKey: "scheme-high-03",
    name: "Высотная укладка с тремя ярусами",
    description: "Трехъярусная схема для средней массы.",
    imageKey: "scheme-inline-03.png",
    tiersCount: 3,
    tierOrderNumber: 1,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-03-iii",
    instructionText: "Подготовить основание из противоскользящих матов и уложить нижний ярус пакетами к центру.",
    tierNote: "Основание должно перекрывать всю площадь контакта.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-high-03-tier-2",
    groupKey: "scheme-high-03",
    name: "Высотная укладка с тремя ярусами",
    description: "Средний ярус с промежуточными балками.",
    imageKey: "scheme-inline-04.png",
    tiersCount: 3,
    tierOrderNumber: 2,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-03-iii",
    instructionText: "Установить промежуточные балки, разложить разделители и собрать второй ярус.",
    tierNote: "Расстояние между балками держать одинаковым.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-high-03-tier-3",
    groupKey: "scheme-high-03",
    name: "Высотная укладка с тремя ярусами",
    description: "Финишный ярус с контрольной стяжкой.",
    imageKey: "scheme-inline-05.png",
    tiersCount: 3,
    tierOrderNumber: 3,
    wagonId: "wagon-gondola-12-532",
    packageTypeId: "pkg-03-iii",
    instructionText: "Собрать третий ярус, установить угловые защиты и выполнить окончательную стяжку.",
    tierNote: "Проверить равномерность натяжения по четырем точкам.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-platform-04-tier-1",
    groupKey: "scheme-platform-04",
    name: "Открытая платформа, прямой ряд",
    description: "Простая одноярусная схема для платформы.",
    imageKey: "scheme-inline-06.png",
    tiersCount: 1,
    tierOrderNumber: 1,
    wagonId: "wagon-platform-13-401",
    packageTypeId: "pkg-04-iv",
    instructionText: "Разложить пакеты в один ряд, установить боковые стойки и закрепить цепями.",
    tierNote: "Особое внимание уделить торцевым упорам.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-platform-05-tier-1",
    groupKey: "scheme-platform-05",
    name: "Открытая платформа, двойной ряд",
    description: "Два яруса с дополнительными балками и стяжкой.",
    imageKey: "scheme-inline-02.png",
    tiersCount: 2,
    tierOrderNumber: 1,
    wagonId: "wagon-platform-13-401",
    packageTypeId: "pkg-05-v",
    instructionText: "Сформировать нижний ряд с упорами и разложить противоскользящие маты между опорными зонами.",
    tierNote: "Проверить плотность установки боковых стоек.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-platform-05-tier-2",
    groupKey: "scheme-platform-05",
    name: "Открытая платформа, двойной ряд",
    description: "Верхний ярус с обвязкой через проушины.",
    imageKey: "scheme-inline-04.png",
    tiersCount: 2,
    tierOrderNumber: 2,
    wagonId: "wagon-platform-13-401",
    packageTypeId: "pkg-05-v",
    instructionText: "Разместить верхний ряд на разделительных балках и выполнить обвязку через проушины платформы.",
    tierNote: "Стяжка затягивается после проверки диагоналей.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-covered-06-tier-1",
    groupKey: "scheme-covered-06",
    name: "Крытый вагон, защищенная укладка",
    description: "Один ярус с усиленной фиксацией внутри вагона.",
    imageKey: "scheme-inline-01.png",
    tiersCount: 1,
    tierOrderNumber: 1,
    wagonId: "wagon-covered-11-280",
    packageTypeId: "pkg-02-ii",
    instructionText: "Разместить пакеты по продольной оси, зафиксировать стойками и проволочной обвязкой.",
    tierNote: "Оставить проход для контрольного обхода вдоль правой стены.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-covered-07-tier-1",
    groupKey: "scheme-covered-07",
    name: "Крытый вагон, трехъярусная схема",
    description: "Нижний ярус с направляющими балками.",
    imageKey: "scheme-inline-02.png",
    tiersCount: 3,
    tierOrderNumber: 1,
    wagonId: "wagon-covered-11-280",
    packageTypeId: "pkg-06-ii",
    instructionText: "Подготовить нижний ярус на деревянных балках и задать направляющие клинья.",
    tierNote: "Проверить высоту балок до начала укладки.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-covered-07-tier-2",
    groupKey: "scheme-covered-07",
    name: "Крытый вагон, трехъярусная схема",
    description: "Средний ярус с распорными рамами.",
    imageKey: "scheme-inline-03.png",
    tiersCount: 3,
    tierOrderNumber: 2,
    wagonId: "wagon-covered-11-280",
    packageTypeId: "pkg-06-ii",
    instructionText: "Установить распорные рамы, собрать второй ярус и закрепить поясными лентами.",
    tierNote: "Контрольное расстояние между рамами 1100 мм.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-covered-07-tier-3",
    groupKey: "scheme-covered-07",
    name: "Крытый вагон, трехъярусная схема",
    description: "Верхний ярус с финальной проверкой фиксации.",
    imageKey: "scheme-inline-05.png",
    tiersCount: 3,
    tierOrderNumber: 3,
    wagonId: "wagon-covered-11-280",
    packageTypeId: "pkg-06-ii",
    instructionText: "Собрать верхний ярус, установить защитные уголки и завершить проволочную фиксацию.",
    tierNote: "Перед закрытием вагона выполнить повторную проверку натяжения.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-halfcar-08-tier-1",
    groupKey: "scheme-halfcar-08",
    name: "Балансированная укладка",
    description: "Одноярусная схема с акцентом на равномерное распределение массы.",
    imageKey: "scheme-inline-06.png",
    tiersCount: 1,
    tierOrderNumber: 1,
    wagonId: "wagon-halfcar-12-753",
    packageTypeId: "pkg-07-iii",
    instructionText: "Уложить пакеты симметрично от центра, выставить боковые упоры и зафиксировать цепями.",
    tierNote: "Отклонение по центру массы не более 3%.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-halfcar-09-tier-1",
    groupKey: "scheme-halfcar-09",
    name: "Сдвоенная укладка в полувагон",
    description: "Нижний ярус со смещением в шахматном порядке.",
    imageKey: "scheme-inline-03.png",
    tiersCount: 2,
    tierOrderNumber: 1,
    wagonId: "wagon-halfcar-12-753",
    packageTypeId: "pkg-08-i",
    instructionText: "Собрать нижний ярус в шахматном порядке, задать клинья и поставить прокладки.",
    tierNote: "Не допускать прямого контакта металла с бортом.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-halfcar-09-tier-2",
    groupKey: "scheme-halfcar-09",
    name: "Сдвоенная укладка в полувагон",
    description: "Финишный ярус с ленточной стяжкой.",
    imageKey: "scheme-inline-04.png",
    tiersCount: 2,
    tierOrderNumber: 2,
    wagonId: "wagon-halfcar-12-753",
    packageTypeId: "pkg-08-i",
    instructionText: "Уложить верхний ярус, установить уголки и затянуть ленточные стяжки по диагонали.",
    tierNote: "После затяжки выполнить повторный обход с обеих сторон.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
  {
    id: "scheme-heavy-10-tier-1",
    groupKey: "scheme-heavy-10",
    name: "Тяжелый пакет, усиленная фиксация",
    description: "Одноярусная схема для тяжелого пакета в усиленном полувагоне.",
    imageKey: "scheme-inline-02.png",
    tiersCount: 1,
    tierOrderNumber: 1,
    wagonId: "wagon-gondola-12-9745",
    packageTypeId: "pkg-06-ii",
    instructionText: "Уложить тяжелые пакеты на усиленные маты, установить стойки и выполнить двойную цепную фиксацию.",
    tierNote: "Проверка крепления обязательна до выпуска вагона.",
    isActive: true,
    version: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
  },
];
