import type { PackageTypeRecord } from "@/src/types/domain";

const timestamp = 1711260000000;

export const packageTypesSeed: PackageTypeRecord[] = [
  {
    id: "pkg-01-i",
    packageTypeNumber: 1,
    constructionVariant: "I",
    nominalIngotMassKg: 980,
    ingotHeightMm: 270,
    packageDimensions: "740 x 740 x 570",
    legHeightMm: 90,
    legBaseMm: 220,
    nominalPackageMassKg: 3920,
    packageMassDeviationKg: 25,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-02-ii",
    packageTypeNumber: 2,
    constructionVariant: "II",
    nominalIngotMassKg: 1020,
    ingotHeightMm: 285,
    packageDimensions: "760 x 760 x 590",
    legHeightMm: 100,
    legBaseMm: 220,
    nominalPackageMassKg: 4080,
    packageMassDeviationKg: 30,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-03-iii",
    packageTypeNumber: 3,
    constructionVariant: "III",
    nominalIngotMassKg: 1080,
    ingotHeightMm: 295,
    packageDimensions: "780 x 780 x 620",
    legHeightMm: 100,
    legBaseMm: 240,
    nominalPackageMassKg: 4320,
    packageMassDeviationKg: 35,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-04-iv",
    packageTypeNumber: 4,
    constructionVariant: "IV",
    nominalIngotMassKg: 1110,
    ingotHeightMm: 300,
    packageDimensions: "790 x 790 x 640",
    legHeightMm: 110,
    legBaseMm: 240,
    nominalPackageMassKg: 4440,
    packageMassDeviationKg: 35,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-05-v",
    packageTypeNumber: 5,
    constructionVariant: "V",
    nominalIngotMassKg: 1140,
    ingotHeightMm: 305,
    packageDimensions: "800 x 800 x 650",
    legHeightMm: 110,
    legBaseMm: 250,
    nominalPackageMassKg: 4560,
    packageMassDeviationKg: 40,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-06-ii",
    packageTypeNumber: 6,
    constructionVariant: "II",
    nominalIngotMassKg: 1160,
    ingotHeightMm: 315,
    packageDimensions: "820 x 820 x 660",
    legHeightMm: 120,
    legBaseMm: 250,
    nominalPackageMassKg: 4640,
    packageMassDeviationKg: 40,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-07-iii",
    packageTypeNumber: 7,
    constructionVariant: "III",
    nominalIngotMassKg: 1180,
    ingotHeightMm: 320,
    packageDimensions: "830 x 830 x 670",
    legHeightMm: 120,
    legBaseMm: 260,
    nominalPackageMassKg: 4720,
    packageMassDeviationKg: 45,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "pkg-08-i",
    packageTypeNumber: 8,
    constructionVariant: "I",
    nominalIngotMassKg: 940,
    ingotHeightMm: 260,
    packageDimensions: "720 x 720 x 540",
    legHeightMm: 90,
    legBaseMm: 210,
    nominalPackageMassKg: 3760,
    packageMassDeviationKg: 20,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
];
