import type { WagonRecord } from "@/src/types/domain";

const timestamp = 1711260000000;

export const wagonsSeed: WagonRecord[] = [
  {
    id: "wagon-gondola-12-532",
    name: "Полувагон 12-532",
    code: "12-532",
    description: "Базовая модель полувагона для пакетной погрузки на складе.",
    capacityKg: 69000,
    innerLengthMm: 12720,
    innerWidthMm: 2870,
    innerHeightMm: 2060,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "wagon-gondola-12-9745",
    name: "Полувагон 12-9745",
    code: "12-9745",
    description: "Усиленный полувагон под тяжелые пакеты.",
    capacityKg: 71000,
    innerLengthMm: 12680,
    innerWidthMm: 2890,
    innerHeightMm: 2100,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "wagon-platform-13-401",
    name: "Платформа 13-401",
    code: "13-401",
    description: "Открытая платформа для крупноразмерных пакетов.",
    capacityKg: 72000,
    innerLengthMm: 13300,
    innerWidthMm: 2870,
    innerHeightMm: 0,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "wagon-covered-11-280",
    name: "Крытый вагон 11-280",
    code: "11-280",
    description: "Крытый вагон для защищенной погрузки и фиксации.",
    capacityKg: 66000,
    innerLengthMm: 13800,
    innerWidthMm: 2770,
    innerHeightMm: 2790,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
  {
    id: "wagon-halfcar-12-753",
    name: "Полувагон 12-753",
    code: "12-753",
    description: "Полувагон для быстрых сменных схем с повышенной устойчивостью.",
    capacityKg: 70000,
    innerLengthMm: 12840,
    innerWidthMm: 2880,
    innerHeightMm: 2140,
    createdAt: timestamp,
    updatedAt: timestamp,
    isDeleted: false,
    syncStatus: "local",
    version: 1,
  },
];
